#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config/{nginx/site-confs,keys} \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx

# generate keys (maybe)
if [[ $DISABLE_HTTPS -ne 1 ]]; then
    if [[ $ENABLE_LETSENCRYPT -eq 1 ]]; then
        if [[ ! -f /config/acme.sh/acme.sh ]]; then
            mkdir /config/acme.sh
            pushd /opt
            sh ./acme.sh --install --home /config/acme.sh --accountemail $LETSENCRYPT_EMAIL
            popd
        fi
        if [[ ! -f /config/acme-certs/$LETSENCRYPT_DOMAIN/fullchain.pem ]]; then
            STAGING=""
            if [[ $LETSENCRYPT_USE_STAGING -eq 1 ]]; then
                STAGING="--staging"
            fi
            export LE_WORKING_DIR="/config/acme.sh"
            # TODO: move away from standalone mode to webroot mode.
            /config/acme.sh/acme.sh \
                $STAGING \
                --issue \
                --standalone \
                --pre-hook "if [[ -f /var/run/s6/services/nginx ]]; then s6-svc -d /var/run/s6/services/nginx; fi" \
                --post-hook "if [[ -f /var/run/s6/services/nginx ]]; then s6-svc -u /var/run/s6/services/nginx; fi" \
                -d $LETSENCRYPT_DOMAIN
            rc=$?
            if [[ $rc -eq 1 ]]; then
                echo "Failed to obtain a certificate from the Let's Encrypt CA."
                # this tries to get the user's attention and to spare the
                # authority's rate limit:
                sleep 15
                echo "Exiting."
                exit 1
            fi
            mkdir -p /config/acme-certs/$LETSENCRYPT_DOMAIN
            if ! /config/acme.sh/acme.sh \
                    --install-cert -d $LETSENCRYPT_DOMAIN \
                    --key-file /config/acme-certs/$LETSENCRYPT_DOMAIN/key.pem  \
                    --fullchain-file /config/acme-certs/$LETSENCRYPT_DOMAIN/fullchain.pem ; then
                echo "Failed to install certificate."
                # this tries to get the user's attention and to spare the
                # authority's rate limit:
                sleep 15
                echo "Exiting."
                exit 1
            fi
        fi
    else
        # use self-signed certs
        if [[ -f /config/keys/cert.key && -f /config/keys/cert.crt ]]; then
            echo "using keys found in /config/keys"
        else
            echo "generating self-signed keys in /config/keys, you can replace these with your own keys if required"
            SUBJECT="/C=US/ST=TX/L=Austin/O=jitsi.org/OU=Jitsi Server/CN=*"
            openssl req -new -x509 -days 3650 -nodes -out /config/keys/cert.crt -keyout /config/keys/cert.key -subj "$SUBJECT"
        fi
    fi
fi

# copy config files
tpl /defaults/nginx.conf > /config/nginx/nginx.conf

tpl /defaults/meet.conf > /config/nginx/meet.conf
if [[ -f /config/nginx/custom-meet.conf ]]; then
    cat /config/nginx/custom-meet.conf >> /config/nginx/meet.conf
fi

tpl /defaults/ssl.conf > /config/nginx/ssl.conf

tpl /defaults/default > /config/nginx/site-confs/default

cp /defaults/config.js /config/config.js
tpl /defaults/system-config.js >> /config/config.js
tpl /defaults/settings-config.js >> /config/config.js
if [[ -f /config/custom-config.js ]]; then
    cat /config/custom-config.js >> /config/config.js
fi

MissedAppName="${CUSTOM_APP_NAME:=Missed.com}"

if [[ ! -f /config/interface_config.js ]]; then
    cp /defaults/interface_config.js /config/interface_config.js

    sed -i \
        -e "s#Missed.com#$MissedAppName#g" \
        /config/interface_config.js

    # It will remove parameter 'closedcaptions' from TOOLBAR_BUTTONS if ENABLE_TRANSCRIPTIONS is false,
    # because it enabled by default, but not supported out of the box.
    if [[ $ENABLE_TRANSCRIPTIONS -ne 1 && "$ENABLE_TRANSCRIPTIONS" != "true" ]]; then
        sed -i \
            -e "s#'closedcaptions', ##" \
            /config/interface_config.js
    fi
fi

# Custom by Rustam
# make custom folders
mkdir -p \
    /config/{css,images,react/features/deep-linking/components,react/features/recording/components/Recording,react/features/welcome/components}

if [[ ! -f /config/title.html ]]; then
    cp /defaults/custom/title.html /config/title.html
    sed -i \
        -e "s#Missed.com#$MissedAppName#g" \
        /config/title.html
fi
# Copy all custom images
if [[ ! -f /config/favicon.ico ]]; then
    cp /defaults/custom/images/favicon.ico /config/favicon.ico
fi

if [[ ! -f /config/images/favicon.ico ]]; then
    cp /defaults/custom/images/favicon.ico /config/images/favicon.ico
fi

if [[ ! -f /config/images/logo.png ]]; then
    cp /defaults/custom/images/logo.png /config/images/logo.png
fi

if [[ ! -f /config/images/logo_square.png ]]; then
    cp /defaults/custom/images/logo_square.png /config/images/logo_square.png
fi

if [[ ! -f /config/images/logo-deep-linking.png ]]; then
    cp /defaults/custom/images/logo-deep-linking.png /config/images/logo-deep-linking.png
fi

if [[ ! -f /config/images/watermark.png ]]; then
    cp /defaults/custom/images/watermark.png /config/images/watermark.png
fi

# Copy all custom CSS
if [[ ! -f /config/css/_welcome_page.scss ]]; then
    cp /defaults/custom/css/_welcome_page.scss /config/css/_welcome_page.scss
fi

# Copy all custom JS
if [[ ! -f /config/react/features/deep-linking/components/DeepLinkingMobilePage.web.js ]]; then
    cp /defaults/custom/react/features/deep-linking/components/DeepLinkingMobilePage.web.js /config/react/features/deep-linking/components/DeepLinkingMobilePage.web.js
fi

if [[ ! -f /config/react/features/recording/components/Recording/styles.native.js ]]; then
    cp /defaults/custom/react/features/recording/components/Recording/styles.native.js /config/react/features/recording/components/Recording/styles.native.js
fi

if [[ ! -f /config/react/features/recording/components/Recording/styles.web.js ]]; then
    cp /defaults/custom/react/features/recording/components/Recording/styles.web.js /config/react/features/recording/components/Recording/styles.web.js
fi

if [[ ! -f /config/react/features/welcome/components/WelcomePage.web.js ]]; then
    cp /defaults/custom/react/features/welcome/components/WelcomePage.web.js /config/react/features/welcome/components/WelcomePage.web.js
fi

