name: Fiesta_CI

on:
  push:
    branches: [ fiesta ]
  pull_request:
    branches: [ fiesta ]

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
  
      # deploy to the main host with git
      - name: Deploy to the main host
        uses: fifsky/ssh-action@master
        env:
          PROJECT_DIR: ${{ secrets.FIESTA_MAIN_PROJECT_LOCATION }}
        with:
          command: |
            cd ${{ secrets.FIESTA_MAIN_PROJECT_LOCATION }}
            git pull origin ${GITHUB_REF##*/}
            exec ${{ secrets.FIESTA_MAIN_PROJECT_LOCATION }}
          host: ${{ secrets.FIESTA_MEET_MAIN_SERVER }}
          user: ubuntu
          key: ${{ secrets.FIESTA_PRIVKEY }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.