name: Fiesta_CI

on:
  push:
    branches: [ fiesta ]
  pull_request:
    branches: [ fiesta ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
  
      - name: Deploy to the main host
        run: echo $FIESTA_PEM_FILE

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.