name: Fiesta_CI

on:
  push:
    branches: [ fiesta ]
  pull_request:
    branches: [ fiesta ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
  
      - name: Deploy to the main host
        env: 
          FIESTA_PEM_FILE: ${{ secrets.FIESTA_PEM_FILE }}
          MAIN_SERVER: ${{ secrets.MAIN_SERVER }}
        run: |
          echo $FIESTA_PEM_FILE >> fiesta.pem
          ssh -i fiesta.pem ubuntu@$MAIN_SERVER 'echo test >> test'

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.