name: Fiesta_CI

on:
  push:
    branches: [ fiesta ]
  pull_request:
    branches: [ fiesta ]

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
  
      # deploy to the main host with git
      - name: Deploy to the main host
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.FIESTA_MAIN_PROJECT_LOCATION }}
            git pull origin ${GITHUB_REF##*/}
            exec ${{ secrets.FIESTA_MAIN_PROJECT_LOCATION }}/build-custom-images.sh
            docker-compose -f docker-compose-custom up -d
            docker tag jitsi/web:custom ${{ secrets.DOCKER_REGISTRY }}/fiesta_jitsi_web
            docker login ${{ secrets.DOCKER_REGISTRY }}
            docker push ${{ secrets.DOCKER_REGISTRY }}/fiesta_jitsi_web
          host: ${{ secrets.FIESTA_MEET_MAIN_SERVER }}
          user: ubuntu
          key: ${{ secrets.FIESTA_PRIVKEY }}
      
      # deploy to other servers with docker
      - name: Deploy to us-west-1
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker login ${{ secrets.DOCKER_REGISTRY }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}/fiesta_jitsi_web
            docker stop ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            docker rm ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            set -a &&. ./.env && set +a
            docker run --detach --volume $CONFIG/web:/config:Z --volume $CONFIG/web/letsencrypt:/etc/letsencrypt:Z --publish $HTTP_PORT:80 --name $JITSI_WEB_CONTAINER_NAME $JITSI_WEB_IMAGE_NAME
          host: ${{ secrets.FIESTA_MEET_US_WEST_1 }}
          user: ubuntu
          key: ${{ secrets.FIESTA_PRIVKEY }}

      - name: Deploy to sa-east-1
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker login ${{ secrets.DOCKER_REGISTRY }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}/fiesta_jitsi_web
            docker stop ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            docker rm ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            set -a &&. ./.env && set +a
            docker run --detach --volume $CONFIG/web:/config:Z --volume $CONFIG/web/letsencrypt:/etc/letsencrypt:Z --publish $HTTP_PORT:80 --name $JITSI_WEB_CONTAINER_NAME $JITSI_WEB_IMAGE_NAME
          host: ${{ secrets.FIESTA_MEET_SA_EAST_1 }}
          user: ubuntu
          key: ${{ secrets.FIESTA_PRIVKEY }}

      - name: Deploy to eu-central-1
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker login ${{ secrets.DOCKER_REGISTRY }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}/fiesta_jitsi_web
            docker stop ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            docker rm ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            set -a &&. ./.env && set +a
            docker run --detach --volume $CONFIG/web:/config:Z --volume $CONFIG/web/letsencrypt:/etc/letsencrypt:Z --publish $HTTP_PORT:80 --name $JITSI_WEB_CONTAINER_NAME $JITSI_WEB_IMAGE_NAME
          host: ${{ secrets.FIESTA_MEET_EU_CENTRAL_1 }}
          user: ubuntu
          key: ${{ secrets.FIESTA_PRIVKEY }}
      
      - name: Deploy to ap-south-1
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker login ${{ secrets.DOCKER_REGISTRY }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}/fiesta_jitsi_web
            docker stop ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            docker rm ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            set -a &&. ./.env && set +a
            docker run --detach --volume $CONFIG/web:/config:Z --volume $CONFIG/web/letsencrypt:/etc/letsencrypt:Z --publish $HTTP_PORT:80 --name $JITSI_WEB_CONTAINER_NAME $JITSI_WEB_IMAGE_NAME
          host: ${{ secrets.FIESTA_MEET_AP_SOUTH_1 }}
          user: ubuntu
          key: ${{ secrets.FIESTA_PRIVKEY }}

      - name: Deploy to ap-east-1
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker login ${{ secrets.DOCKER_REGISTRY }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}/fiesta_jitsi_web
            docker stop ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            docker rm ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            set -a &&. ./.env && set +a
            docker run --detach --volume $CONFIG/web:/config:Z --volume $CONFIG/web/letsencrypt:/etc/letsencrypt:Z --publish $HTTP_PORT:80 --name $JITSI_WEB_CONTAINER_NAME $JITSI_WEB_IMAGE_NAME
          host: ${{ secrets.FIESTA_MEET_AP_EAST_1 }}
          user: ubuntu
          key: ${{ secrets.FIESTA_PRIVKEY }}

      - name: Deploy to ap-southeast-1
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker login ${{ secrets.DOCKER_REGISTRY }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}/fiesta_jitsi_web
            docker stop ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            docker rm ${{ secrets.FIESTA_WEB_CONTAINER_NAME }}
            set -a &&. ./.env && set +a
            docker run --detach --volume $CONFIG/web:/config:Z --volume $CONFIG/web/letsencrypt:/etc/letsencrypt:Z --publish $HTTP_PORT:80 --name $JITSI_WEB_CONTAINER_NAME $JITSI_WEB_IMAGE_NAME
          host: ${{ secrets.FIESTA_MEET_AP_SOUTHEAST_1 }}
          user: ubuntu
          key: ${{ secrets.FIESTA_PRIVKEY }}
        
          