name: Fiesta_CI

on:
  push:
    branches: [ fiesta ]
  pull_request:
    branches: [ fiesta ]

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
  
      - name: Deploy to the main host
        uses: fifsky/ssh-action@master
        env:
          PROJECT_DIR: ${{ secrets.FIESTA_MAIN_PROJECT_LOCATION }}
        with:
          command: |
            cd $PROJECT_DIR
            git pull origin ${GITHUB_REF##*/}
            exec $PROJECT_DIR/build-custom-images.sh
          host: ${{ secrets.FIESTA_MEET_MAIN_SERVER }}
          user: ubuntu
          key: ${{ secrets.FIESTA_PRIVKEY }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.